Creating a Management script

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -1,31 +1,14 @@
 #!/usr/bin/env bash
 
-# Reset
 Color_Off='\033[0m'       # Text Reset
-
-# Regular Colors
-Black='\033[0;30m'        # Black
-Red='\033[0;31m'          # Red
-Green='\033[0;32m'        # Green
-Yellow='\033[0;33m'       # Yellow
-Blue='\033[0;34m'         # Blue
-Purple='\033[0;35m'       # Purple
-Cyan='\033[0;36m'         # Cyan
 White='\033[0;37m'        # White
-
-# Bold
-BBlack='\033[1;30m'       # Black
-BRed='\033[1;31m'         # Red
-BGreen='\033[1;32m'       # Green
-BYellow='\033[1;33m'      # Yellow
-BBlue='\033[1;34m'        # Blue
-BPurple='\033[1;35m'      # Purple
 BCyan='\033[1;36m'        # Cyan
-BWhite='\033[1;37m'       # White
 
 printf "\033c" # Clear screen
 
-printf "${BCyan}"
+help_env() {
+
+    printf "${BCyan}"
 cat << "EOF"
   _____  ____  _____  ___  ____
  / ___/ /    ||     |/  _]|    \
@@ -35,21 +18,56 @@ cat << "EOF"
  \    ||  |  ||  | |     ||  .  \
   \___||__|__||__| |_____||__|\_|
 EOF
-printf "${Color_Off}"
+    printf "${Color_Off}"
 
-printf "\n${White}Booting up Docker Containers...${Color_Off}\n"
-docker-compose up -d
-OUTPUT=$(docker exec -ti saferhiddenservice onions --json | python -c "import sys, json; print json.load(sys.stdin)['safer'][0].split(':')[0]")
-URL="http://${OUTPUT}/"
+    echo "------------------------------------------------------------------------"
+    echo "Usage: `basename $0` [-h]"
+    echo "Usage: $0 [option...] --{init|start|halt|clean|stats}"
+    echo ""
+    echo "   --- MANAGEMENT ---"
+    echo "   -i, --init, init           Initializes the development environment."
+    echo "   -s, --start, start         Starts all configured services."
+    echo "   -p, --halt, halt           Stops all configured services."
+    echo "   -r, --relaod, reload       Restart all configured services."
+    echo "   -b, --rebuild, rebuild     Rebuild all configured services."
+    echo "   -c, --clean, clean         Cleans containers, volumes, images."
+    echo ""
+    echo "   --- UTILITIES ---"
+    echo "   -o, --onion, onion         Get the onion URL."
+    echo "   -h, --help, help           Shows this help box."
+    echo "------------------------------------------------------------------------"
+}
 
-printf "\n${White}Finding the .onion URL...${Color_Off}\n"
-printf "${White}${BCyan}$OUTPUT${Color_Off}\n"
-
-printf "\n${White}Adding an ${BCyan}upload${White} function to your ${BCyan}.bash_profile${White} file...${Color_Off}\n"
-printf "${Yellow}"
-COMMAND="function upload() { printf \"Uploading file...\n\"; curl --socks5-hostname 127.0.0.1:9050 -H 'Expect:' -F \"file=@\${1}\" -F \"password=\${2}\" http://tx6j66gbja42nvg6sreumixajlwknlpngdysdw6fbkff3pydptwa26id.onion/file/upload; printf \"\nDone.\n\"; }"
-echo $COMMAND >> ~/.bash_profile
-printf "${Color_Off}"
-printf "\n"
-source ~/.bash_profile
-
+SCRIPT_DIR=$(dirname "$0")/scripts
+while :
+do
+  OPT=$(echo "$1" | awk '{print tolower($0)}')
+  case "$OPT" in
+    -h | --help | help | "")
+      help_env
+      break ;;
+    -i | --init | init)
+      bash ${SCRIPT_DIR}/init.sh; # System initialization
+      break ;;
+    -s | --start | start)
+      bash ${SCRIPT_DIR}/start.sh; # Start all services
+      break ;;
+    -p | --halt | halt)
+      bash ${SCRIPT_DIR}/stop.sh; # Stop all services
+      break ;;
+    -r | --reload | reload)
+      bash ${SCRIPT_DIR}/reload.sh; # Reload all services
+      break ;;
+    -c | --clean | clean)
+      bash ${SCRIPT_DIR}/clean.sh; # Clean everything
+      break ;;
+    -o | --onion | onion)
+      bash ${SCRIPT_DIR}/get-onion.sh; # Get the onion URL
+      break ;;
+    *)
+      echo "Error: Unknown option: $1" >&2
+      help_env
+      exit 1 ;;
+    *)
+  esac
+done
